package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1



/**
 * LcCiudad generated by hbm2java
 */
public class LcCiudad  implements java.io.Serializable {


     private int idCiudad;
     private LcProvincia lcProvincia;
     private String ciudad;
     private String estado;

    public LcCiudad() {
    }

	
    public LcCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public LcCiudad(int idCiudad, LcProvincia lcProvincia, String ciudad, String estado) {
       this.idCiudad = idCiudad;
       this.lcProvincia = lcProvincia;
       this.ciudad = ciudad;
       this.estado = estado;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public LcProvincia getLcProvincia() {
        return this.lcProvincia;
    }
    
    public void setLcProvincia(LcProvincia lcProvincia) {
        this.lcProvincia = lcProvincia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


