package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcClientes generated by hbm2java
 */
public class LcClientes  implements java.io.Serializable {


     private int idCliente;
     private LcEmpresa lcEmpresa;
     private String tipoIdentificacion;
     private String identificacion;
     private String razonSocial;
     private String direccion;
     private String pais;
     private Integer provincia;
     private String ciudad;
     private String contacto;
     private String email;
     private String telefono;
     private String extensioon;
     private String celular;
     private Date fechaCreacion;
     private String estado;

    public LcClientes() {
    }

	
    public LcClientes(int idCliente) {
        this.idCliente = idCliente;
    }
    public LcClientes(int idCliente, LcEmpresa lcEmpresa, String tipoIdentificacion, String identificacion, String razonSocial, String direccion, String pais, Integer provincia, String ciudad, String contacto, String email, String telefono, String extensioon, String celular, Date fechaCreacion, String estado) {
       this.idCliente = idCliente;
       this.lcEmpresa = lcEmpresa;
       this.tipoIdentificacion = tipoIdentificacion;
       this.identificacion = identificacion;
       this.razonSocial = razonSocial;
       this.direccion = direccion;
       this.pais = pais;
       this.provincia = provincia;
       this.ciudad = ciudad;
       this.contacto = contacto;
       this.email = email;
       this.telefono = telefono;
       this.extensioon = extensioon;
       this.celular = celular;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public LcEmpresa getLcEmpresa() {
        return this.lcEmpresa;
    }
    
    public void setLcEmpresa(LcEmpresa lcEmpresa) {
        this.lcEmpresa = lcEmpresa;
    }
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Integer getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Integer provincia) {
        this.provincia = provincia;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getExtensioon() {
        return this.extensioon;
    }
    
    public void setExtensioon(String extensioon) {
        this.extensioon = extensioon;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


