package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcDeudor generated by hbm2java
 */
public class LcDeudor  implements java.io.Serializable {


     private int idDeudor;
     private Integer idEmpresa;
     private Integer idCliente;
     private String nombreCartera;
     private String observacion;
     private String datosAdicional;
     private Date fechaCreacion;
     private Date fechaActualizacion;
     private String estado;

    public LcDeudor() {
    }

	
    public LcDeudor(int idDeudor) {
        this.idDeudor = idDeudor;
    }
    public LcDeudor(int idDeudor, Integer idEmpresa, Integer idCliente, String nombreCartera, String observacion, String datosAdicional, Date fechaCreacion, Date fechaActualizacion, String estado) {
       this.idDeudor = idDeudor;
       this.idEmpresa = idEmpresa;
       this.idCliente = idCliente;
       this.nombreCartera = nombreCartera;
       this.observacion = observacion;
       this.datosAdicional = datosAdicional;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.estado = estado;
    }
   
    public int getIdDeudor() {
        return this.idDeudor;
    }
    
    public void setIdDeudor(int idDeudor) {
        this.idDeudor = idDeudor;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCartera() {
        return this.nombreCartera;
    }
    
    public void setNombreCartera(String nombreCartera) {
        this.nombreCartera = nombreCartera;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getDatosAdicional() {
        return this.datosAdicional;
    }
    
    public void setDatosAdicional(String datosAdicional) {
        this.datosAdicional = datosAdicional;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


