package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcEmpleados generated by hbm2java
 */
public class LcEmpleados  implements java.io.Serializable {


     private int idEmpleado;
     private LcCargos lcCargos;
     private LcEmpresa lcEmpresa;
     private String tipoIdentificacion;
     private String identificacion;
     private String nombres;
     private String apellidos;
     private String lugarNacimiento;
     private Date fechaNacimiento;
     private String email;
     private String telefonos;
     private String celular;
     private String direccionDomicilio;
     private String estadoCivil;
     private String genero;
     private String profesion;
     private Integer idJefeInmediato;
     private String observacion;
     private Date fechaCreacion;
     private Date fechaActualizacion;
     private String estado;

    public LcEmpleados() {
    }

	
    public LcEmpleados(int idEmpleado, LcEmpresa lcEmpresa) {
        this.idEmpleado = idEmpleado;
        this.lcEmpresa = lcEmpresa;
    }
    public LcEmpleados(int idEmpleado, LcCargos lcCargos, LcEmpresa lcEmpresa, String tipoIdentificacion, String identificacion, String nombres, String apellidos, String lugarNacimiento, Date fechaNacimiento, String email, String telefonos, String celular, String direccionDomicilio, String estadoCivil, String genero, String profesion, Integer idJefeInmediato, String observacion, Date fechaCreacion, Date fechaActualizacion, String estado) {
       this.idEmpleado = idEmpleado;
       this.lcCargos = lcCargos;
       this.lcEmpresa = lcEmpresa;
       this.tipoIdentificacion = tipoIdentificacion;
       this.identificacion = identificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.lugarNacimiento = lugarNacimiento;
       this.fechaNacimiento = fechaNacimiento;
       this.email = email;
       this.telefonos = telefonos;
       this.celular = celular;
       this.direccionDomicilio = direccionDomicilio;
       this.estadoCivil = estadoCivil;
       this.genero = genero;
       this.profesion = profesion;
       this.idJefeInmediato = idJefeInmediato;
       this.observacion = observacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.estado = estado;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public LcCargos getLcCargos() {
        return this.lcCargos;
    }
    
    public void setLcCargos(LcCargos lcCargos) {
        this.lcCargos = lcCargos;
    }
    public LcEmpresa getLcEmpresa() {
        return this.lcEmpresa;
    }
    
    public void setLcEmpresa(LcEmpresa lcEmpresa) {
        this.lcEmpresa = lcEmpresa;
    }
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getLugarNacimiento() {
        return this.lugarNacimiento;
    }
    
    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDireccionDomicilio() {
        return this.direccionDomicilio;
    }
    
    public void setDireccionDomicilio(String direccionDomicilio) {
        this.direccionDomicilio = direccionDomicilio;
    }
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public Integer getIdJefeInmediato() {
        return this.idJefeInmediato;
    }
    
    public void setIdJefeInmediato(Integer idJefeInmediato) {
        this.idJefeInmediato = idJefeInmediato;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


