package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LcEmpresa generated by hbm2java
 */
public class LcEmpresa  implements java.io.Serializable {


     private int idEmpresa;
     private String idPais;
     private String idCiudad;
     private Integer idProvincia;
     private String tipoIdentificacion;
     private String identificacion;
     private String razonSocial;
     private String direccion;
     private String telefonos;
     private String email;
     private Date fechaCreacion;
     private Date fechaActualizacion;
     private String estado;
     private String telfonos2;
     private String celular;
     private Integer sucursal;
     private Set lcRoleses = new HashSet(0);
     private Set lcEmpleadoses = new HashSet(0);
     private Set lcAgencias = new HashSet(0);
     private Set lcZonases = new HashSet(0);
     private Set lcUsuarioses = new HashSet(0);
     private Set lcCargoses = new HashSet(0);
     private Set lcClienteses = new HashSet(0);

    public LcEmpresa() {
    }

	
    public LcEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public LcEmpresa(int idEmpresa, String idPais, String idCiudad, Integer idProvincia, String tipoIdentificacion, String identificacion, String razonSocial, String direccion, String telefonos, String email, Date fechaCreacion, Date fechaActualizacion, String estado, String telfonos2, String celular, Integer sucursal, Set lcRoleses, Set lcEmpleadoses, Set lcAgencias, Set lcZonases, Set lcUsuarioses, Set lcCargoses, Set lcClienteses) {
       this.idEmpresa = idEmpresa;
       this.idPais = idPais;
       this.idCiudad = idCiudad;
       this.idProvincia = idProvincia;
       this.tipoIdentificacion = tipoIdentificacion;
       this.identificacion = identificacion;
       this.razonSocial = razonSocial;
       this.direccion = direccion;
       this.telefonos = telefonos;
       this.email = email;
       this.fechaCreacion = fechaCreacion;
       this.fechaActualizacion = fechaActualizacion;
       this.estado = estado;
       this.telfonos2 = telfonos2;
       this.celular = celular;
       this.sucursal = sucursal;
       this.lcRoleses = lcRoleses;
       this.lcEmpleadoses = lcEmpleadoses;
       this.lcAgencias = lcAgencias;
       this.lcZonases = lcZonases;
       this.lcUsuarioses = lcUsuarioses;
       this.lcCargoses = lcCargoses;
       this.lcClienteses = lcClienteses;
    }
   
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(String idPais) {
        this.idPais = idPais;
    }
    public String getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(String idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTelfonos2() {
        return this.telfonos2;
    }
    
    public void setTelfonos2(String telfonos2) {
        this.telfonos2 = telfonos2;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Integer getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Integer sucursal) {
        this.sucursal = sucursal;
    }
    public Set getLcRoleses() {
        return this.lcRoleses;
    }
    
    public void setLcRoleses(Set lcRoleses) {
        this.lcRoleses = lcRoleses;
    }
    public Set getLcEmpleadoses() {
        return this.lcEmpleadoses;
    }
    
    public void setLcEmpleadoses(Set lcEmpleadoses) {
        this.lcEmpleadoses = lcEmpleadoses;
    }
    public Set getLcAgencias() {
        return this.lcAgencias;
    }
    
    public void setLcAgencias(Set lcAgencias) {
        this.lcAgencias = lcAgencias;
    }
    public Set getLcZonases() {
        return this.lcZonases;
    }
    
    public void setLcZonases(Set lcZonases) {
        this.lcZonases = lcZonases;
    }
    public Set getLcUsuarioses() {
        return this.lcUsuarioses;
    }
    
    public void setLcUsuarioses(Set lcUsuarioses) {
        this.lcUsuarioses = lcUsuarioses;
    }
    public Set getLcCargoses() {
        return this.lcCargoses;
    }
    
    public void setLcCargoses(Set lcCargoses) {
        this.lcCargoses = lcCargoses;
    }
    public Set getLcClienteses() {
        return this.lcClienteses;
    }
    
    public void setLcClienteses(Set lcClienteses) {
        this.lcClienteses = lcClienteses;
    }




}


