package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1



/**
 * LcEstadoCivil generated by hbm2java
 */
public class LcEstadoCivil  implements java.io.Serializable {


     private int idEstcivil;
     private String abreviatura;
     private String descripcion;
     private String estado;

    public LcEstadoCivil() {
    }

	
    public LcEstadoCivil(int idEstcivil) {
        this.idEstcivil = idEstcivil;
    }
    public LcEstadoCivil(int idEstcivil, String abreviatura, String descripcion, String estado) {
       this.idEstcivil = idEstcivil;
       this.abreviatura = abreviatura;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdEstcivil() {
        return this.idEstcivil;
    }
    
    public void setIdEstcivil(int idEstcivil) {
        this.idEstcivil = idEstcivil;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


