package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcModuloRol generated by hbm2java
 */
public class LcModuloRol  implements java.io.Serializable {


     private int idModuloRol;
     private LcModulos lcModulos;
     private LcRoles lcRoles;
     private Integer idEmpresa;
     private Integer nivelModulo;
     private Integer grupoMod;
     private Date fechaCreacion;
     private String estado;

    public LcModuloRol() {
    }

	
    public LcModuloRol(int idModuloRol) {
        this.idModuloRol = idModuloRol;
    }
    public LcModuloRol(int idModuloRol, LcModulos lcModulos, LcRoles lcRoles, Integer idEmpresa, Integer nivelModulo, Integer grupoMod, Date fechaCreacion, String estado) {
       this.idModuloRol = idModuloRol;
       this.lcModulos = lcModulos;
       this.lcRoles = lcRoles;
       this.idEmpresa = idEmpresa;
       this.nivelModulo = nivelModulo;
       this.grupoMod = grupoMod;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
    }
   
    public int getIdModuloRol() {
        return this.idModuloRol;
    }
    
    public void setIdModuloRol(int idModuloRol) {
        this.idModuloRol = idModuloRol;
    }
    public LcModulos getLcModulos() {
        return this.lcModulos;
    }
    
    public void setLcModulos(LcModulos lcModulos) {
        this.lcModulos = lcModulos;
    }
    public LcRoles getLcRoles() {
        return this.lcRoles;
    }
    
    public void setLcRoles(LcRoles lcRoles) {
        this.lcRoles = lcRoles;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public Integer getNivelModulo() {
        return this.nivelModulo;
    }
    
    public void setNivelModulo(Integer nivelModulo) {
        this.nivelModulo = nivelModulo;
    }
    public Integer getGrupoMod() {
        return this.grupoMod;
    }
    
    public void setGrupoMod(Integer grupoMod) {
        this.grupoMod = grupoMod;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


