package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1



/**
 * LcPais generated by hbm2java
 */
public class LcPais  implements java.io.Serializable {


     private int idPais;
     private String pais;
     private String codigo;
     private String estado;

    public LcPais() {
    }

	
    public LcPais(int idPais) {
        this.idPais = idPais;
    }
    public LcPais(int idPais, String pais, String codigo, String estado) {
       this.idPais = idPais;
       this.pais = pais;
       this.codigo = codigo;
       this.estado = estado;
    }
   
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


