package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LcProvincia generated by hbm2java
 */
public class LcProvincia  implements java.io.Serializable {


     private int idProvincia;
     private Integer idPais;
     private String provincia;
     private String estado;
     private Set lcCiudads = new HashSet(0);

    public LcProvincia() {
    }

	
    public LcProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }
    public LcProvincia(int idProvincia, Integer idPais, String provincia, String estado, Set lcCiudads) {
       this.idProvincia = idProvincia;
       this.idPais = idPais;
       this.provincia = provincia;
       this.estado = estado;
       this.lcCiudads = lcCiudads;
    }
   
    public int getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(int idProvincia) {
        this.idProvincia = idProvincia;
    }
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getLcCiudads() {
        return this.lcCiudads;
    }
    
    public void setLcCiudads(Set lcCiudads) {
        this.lcCiudads = lcCiudads;
    }




}


