package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1



/**
 * LcTiposIdentificacion generated by hbm2java
 */
public class LcTiposIdentificacion  implements java.io.Serializable {


     private int idTipoIdentificacion;
     private String tipoIdentificacion;
     private String descripcion;
     private String estado;

    public LcTiposIdentificacion() {
    }

	
    public LcTiposIdentificacion(int idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public LcTiposIdentificacion(int idTipoIdentificacion, String tipoIdentificacion, String descripcion, String estado) {
       this.idTipoIdentificacion = idTipoIdentificacion;
       this.tipoIdentificacion = tipoIdentificacion;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdTipoIdentificacion() {
        return this.idTipoIdentificacion;
    }
    
    public void setIdTipoIdentificacion(int idTipoIdentificacion) {
        this.idTipoIdentificacion = idTipoIdentificacion;
    }
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


