package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcUsuarios generated by hbm2java
 */
public class LcUsuarios  implements java.io.Serializable {


     private int idUsuario;
     private LcEmpresa lcEmpresa;
     private LcRoles lcRoles;
     private Integer idEmpleado;
     private String usuario;
     private String contrasenia;
     private String observacion;
     private Date fechaCreacion;
     private String estado;

    public LcUsuarios() {
    }

	
    public LcUsuarios(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public LcUsuarios(int idUsuario, LcEmpresa lcEmpresa, LcRoles lcRoles, Integer idEmpleado, String usuario, String contrasenia, String observacion, Date fechaCreacion, String estado) {
       this.idUsuario = idUsuario;
       this.lcEmpresa = lcEmpresa;
       this.lcRoles = lcRoles;
       this.idEmpleado = idEmpleado;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.observacion = observacion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public LcEmpresa getLcEmpresa() {
        return this.lcEmpresa;
    }
    
    public void setLcEmpresa(LcEmpresa lcEmpresa) {
        this.lcEmpresa = lcEmpresa;
    }
    public LcRoles getLcRoles() {
        return this.lcRoles;
    }
    
    public void setLcRoles(LcRoles lcRoles) {
        this.lcRoles = lcRoles;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


