package com.laticobsa.modelo;
// Generated 31/03/2017 06:57:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LcZonas generated by hbm2java
 */
public class LcZonas  implements java.io.Serializable {


     private int idZona;
     private LcEmpresa lcEmpresa;
     private String idPais;
     private Integer idProvincia;
     private String idCiudad;
     private String nombreZona;
     private String sectorDescripcion;
     private Date fechaCreacion;
     private String estado;

    public LcZonas() {
    }

	
    public LcZonas(int idZona) {
        this.idZona = idZona;
    }
    public LcZonas(int idZona, LcEmpresa lcEmpresa, String idPais, Integer idProvincia, String idCiudad, String nombreZona, String sectorDescripcion, Date fechaCreacion, String estado) {
       this.idZona = idZona;
       this.lcEmpresa = lcEmpresa;
       this.idPais = idPais;
       this.idProvincia = idProvincia;
       this.idCiudad = idCiudad;
       this.nombreZona = nombreZona;
       this.sectorDescripcion = sectorDescripcion;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
    }
   
    public int getIdZona() {
        return this.idZona;
    }
    
    public void setIdZona(int idZona) {
        this.idZona = idZona;
    }
    public LcEmpresa getLcEmpresa() {
        return this.lcEmpresa;
    }
    
    public void setLcEmpresa(LcEmpresa lcEmpresa) {
        this.lcEmpresa = lcEmpresa;
    }
    public String getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(String idPais) {
        this.idPais = idPais;
    }
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(String idCiudad) {
        this.idCiudad = idCiudad;
    }
    public String getNombreZona() {
        return this.nombreZona;
    }
    
    public void setNombreZona(String nombreZona) {
        this.nombreZona = nombreZona;
    }
    public String getSectorDescripcion() {
        return this.sectorDescripcion;
    }
    
    public void setSectorDescripcion(String sectorDescripcion) {
        this.sectorDescripcion = sectorDescripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


